### ISSUE TITLE
[BUG] - myelectricaldata beta 0.8.14-beta3

### ISSUE THREAD

**Issue by Sonic62** [MyElectricalData/myelectricaldata#296]
Hello

petit souci lors du lancement de la passerelle ...

![Capture d'écran_20230207_030941](https://user-images.githubusercontent.com/103725660/217282445-a1c40bce-0abc-4462-a603-2be5a7b0422d.png)

**Comment by m4dm4rtig4n** [comment]
A tu encore le soucis ?

**Comment by Sonic62** [comment]
Hello

no c'est OK , cela venait que mon Asus RT88U bloqué via une mise a jour
![Capture d’écran 2023-04-01 231239](https://user-images.githubusercontent.com/103725660/229314200-843faa72-752c-49b6-a43e-f2dadc0a76ef.png)
