### ISSUE TITLE
[BUG] - Plus de remontée dans l'IHM 0.8.14-beta3

### ISSUE THREAD

**Issue by dudu7731** [MyElectricalData/myelectricaldata#302]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Plus de données dans l'IHm depuis le 20/02 : 
![image](https://user-images.githubusercontent.com/117290248/221435336-c9b9cc16-772f-42c3-9118-b29462a356bb.png)
![image](https://user-images.githubusercontent.com/117290248/221435365-b73280f1-b577-4ce7-bd38-28fe1aa1aefb.png)
![image](https://user-images.githubusercontent.com/117290248/221435463-6662489d-2802-44a9-8760-6a0dae6f3928.png)

Pourtant j'ai tenté de vider les caches et de relancer les import mais pas d'évolution

Aussi fait troublant, il semblerait qu'il y aurait de données relatives aux jour non mentionnés sur l'IHM dans influxDB : 
![image](https://user-images.githubusercontent.com/117290248/221435613-fb38291a-6671-4369-b8b2-f34ceafdb976.png)

**Configuration**
myelectricaldata:
  'XXXXXXXXXXXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.174'
    consumption_price_hc: '0.1615'
    consumption_price_hp: '0.2228'
    enable: 'true'
    name: Home Enedis
    offpeak_hours_0: 22h00-06h00
    offpeak_hours_1: 22h00-06h00
    offpeak_hours_2: 22h00-06h00
    offpeak_hours_3: 22h00-06h00
    offpeak_hours_4: 22h00-06h00
    offpeak_hours_5: 22h00-06h00
    offpeak_hours_6: 22h00-06h00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: XXXXXXXXXXXX
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508

**Type d'installation**
Docker

![image](https://user-images.githubusercontent.com/117290248/221435693-247b2aca-0ac3-4907-943d-1b582397a53d.png)

**Comment by m4dm4rtig4n** [comment]
@pbranly c'est le même soucis que tu m'avais signaler sur Discord je présume ?

**Comment by pbranly** [comment]
Oui exactement le même problème
Hier encore, tout était bloqué depuis 5 jours. Ce matin , j'ai restart le docker et c'est redevenu bon.
Et c'est spécifique à la page web car les données sont bien envoyées vers mqtt et influx

**Comment by dudu7731** [comment]
Oui un restart du container a remis les données à jour ...

**Comment by dudu7731** [comment]
pour suivi : 
Je viens de regarder ce matin : 
même problème : 
![image](https://user-images.githubusercontent.com/117290248/222080904-858dc4eb-02f2-4b21-82f4-f65fd11507db.png)

pour info j'ai le même soucis sur la version actuelle (non dev).

**Comment by m4dm4rtig4n** [comment]
J'ai effectuer quelques changement sur la 0.9.0-beta1.

Reste à tester et voir si vous rencontrez encore ce genre de soucis :)
