### ISSUE TITLE
[FEATURES] - Ajouter une page de login

### ISSUE THREAD

**Issue by riadht02** [MyElectricalData/myelectricaldata#303]
j'utilise l'image docker, et je vous demande l'ajout d'une page d'authentification.
Je veux exposer publier le site sans exposer mes données.

Merci.

**Comment by pbranly** [comment]
Hello 
Sans faire de modification côté serveur, l'idéal est de configurer un reverse proxy avec login password.
Phil

**Comment by m4dm4rtig4n** [comment]
Ce n'est pas prévu pour l'instant.
