### ISSUE TITLE
[BUG] - Intégration Lovelace Linky card

### ISSUE THREAD

**Issue by flouck** [MyElectricalData/myelectricaldata#305]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Merci de me détailler au mieux le bug et une procédure pour le reproduire si possible.

Avant, j'utilisais enedisGateway de saniho (https://github.com/saniho/apiEnedis) avec la carte Lovelace Linky (https://github.com/saniho/content-card-linky). 
La remontée d'information a l'air de se faire correctement pour la plupart des informations mais je remarque quelques infos étranges :
- dans l'onglet MyElectricalData, la répartition HP/HC ne correspond pas à mon usage

![image](https://user-images.githubusercontent.com/60158607/222057871-2e9860d4-9090-42a4-aedd-ddf6ed534914.png)

- la carte de saniho affiche au moins deux infos étranges

![image](https://user-images.githubusercontent.com/60158607/222058002-765c8508-3c75-417a-b5fe-98dea551e567.png)

J'ai attendu 48h mais j'ai toujours ces infos surprenantes.

**Configuration**
Il me faut la partie enedis_gateway de votre config.yml, sans les PDL et Token.

Voici ce qui est dans le fichier config.yaml de myelectricaldata.

```
cycle: 14400
debug: false
home_assistant:
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: "abc123"
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: addons
myelectricaldata:
    "123":
      addresses: true
      activation_date_daily: ''
      activation_date_detail: ''
      cache: true
      consumption: true
      consumption_detail: true
      consumption_detail_max_date: ''
      consumption_max_date: ''
      consumption_price_base: 0
      consumption_price_hc: 0.141426
      consumption_price_hp: 0.182574
      enable: true
      name: "elec1"
      offpeak_hours_0: 22H30-6H30
      offpeak_hours_1: 22H30-6H30
      offpeak_hours_2: 22H30-6H30
      offpeak_hours_3: 22H30-6H30
      offpeak_hours_4: 22H30-6H30
      offpeak_hours_5: 22H30-6H30
      offpeak_hours_6: 22H30-6H30
      plan: HP/HC
      production: false
      production_detail: false
      production_detail_max_date: ''
      production_max_date: ''
      production_price: 0
      refresh_addresse: false
      refresh_contract: true
      token: "abc123"
    "123":
      addresses: true
      activation_date_daily: ''
      activation_date_detail: ''
      cache: true
      consumption: true
      consumption_detail: true
      consumption_detail_max_date: ''
      consumption_max_date: ''
      consumption_price_base: 0
      consumption_price_hc: 0.147
      consumption_price_hp: 0.1841
      enable: true
      name: "elec2"
      offpeak_hours_0: 23H04-7H04
      offpeak_hours_1: 23H04-7H04
      offpeak_hours_2: 23H04-7H04
      offpeak_hours_3: 23H04-7H04
      offpeak_hours_4: 23H04-7H04
      offpeak_hours_5: 23H04-7H04
      offpeak_hours_6: 23H04-7H04
      plan: HP/HC
      production: false
      production_detail: false
      production_detail_max_date: ''
      production_max_date: ''
      production_price: 0
      refresh_addresse: false
      refresh_contract: true
      token: "abc123"


```

**Type d'installation**
Docker, HassIO ?

HassIo via l'addon de Alexbelgium

**Version : X.X.X**

**Comment by vingerha** [comment]
stp copier le contenu de ton entity sensor.myelectricaldata_consumption_[pdl], avec tous ces attributes

**Comment by flouck** [comment]
Voila :-)
D'autant que je crois que les valeurs par jours sont erronées par rapport à ce que je trouve sur le site de mon fournisseur...

```
numPDL: 'xxx'
activationDate: '2016-12-24 00:00:00'
lastUpdate: '2023-03-02 17:38:41'
timeLastCall: '2023-03-02 17:38:41'
yesterdayDate: '2023-03-01'
yesterday: 89.7
ServiceEnedis: myElectricalData
yesterdayLastYearDate: '2022-03-02'
yesterdayLastYear: 72.39
daily:
  - 89.7
  - 99.35
  - 106.68
  - 124.22
  - 93.58
  - 63.06
  - 53.35
current_week: 629.95
last_week: 368.58
day_1: 89.7
day_2: 99.35
day_3: 106.68
day_4: 124.22
day_5: 93.58
day_6: 63.06
day_7: 53.35
current_week_last_year: 785.93
last_month: 2181.82
current_month: 89.7
current_month_last_year: 72.39
last_month_last_year: 2337.4
last_year: 7617.18
current_year: 3823.67
current_year_last_year: 3194.32
dailyweek:
  - '2023-03-01'
  - '2023-02-28'
  - '2023-02-27'
  - '2023-02-26'
  - '2023-02-25'
  - '2023-02-24'
  - '2023-02-23'
dailyweek_cost:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
dailyweek_costHP:
  - 9.5
  - 11.1
  - 11.4
  - 13.9
  - 11.9
  - 6.9
  - 3.6
dailyweek_HP:
  - 51.7
  - 60.36
  - 61.68
  - 75.48
  - 64.54
  - 37.26
  - 19.34
daily_cost: 0
yesterday_HP_cost: 9.5
yesterday_HP: 51.7
day_1_HP: 51708
day_2_HP: 60366
day_3_HP: 61683
day_4_HP: 75480
day_5_HP: 64543
day_6_HP: 37269
day_7_HP: 19341
dailyweek_costHC:
  - 5.6
  - 5.7
  - 6.6
  - 7.2
  - 4.3
  - 3.8
  - 5
dailyweek_HC:
  - 37.99
  - 38.98
  - 44.99
  - 48.74
  - 29.03
  - 25.79
  - 34.01
yesterday_HC_cost: 5.6
yesterday_HC: 37.99
day_1_HC: 37999
day_2_HC: 38984
day_3_HC: 44999
day_4_HC: 48747
day_5_HC: 29037
day_6_HC: 25793
day_7_HC: 34010
peak_offpeak_percent: 1852.23
YesterdayConsumptionMaxPower: 6543
dailyweek_MP:
  - 6.54
  - 7.77
  - 8.77
  - 9.75
  - 9.04
  - 6.53
  - 7.86
dailyweek_MP_over:
  - 'false'
  - 'false'
  - 'false'
  - 'true'
  - 'true'
  - 'false'
  - 'false'
monthly_evolution: -6.66
current_week_evolution: 70.91
current_month_evolution: 23.92
yesterday_evolution: -9.71
friendly_name: myelectricaldata_consumption_xxx
errorLastCall: ''
errorLastCallInterne: ''
current_week_number: '09'
offpeak_hours_enedis: >-
  Lundi (23H04-7H04);Mardi (23H04-7H04);Mercredi (23H04-7H04);Jeudi
  (23H04-7H04);Vendredi (23H04-7H04);Samedi (23H04-7H04);Dimanche (23H04-7H04);
offpeak_hours:
  - - - 23H04
      - 7H04
  - - - 23H04
      - 7H04
  - - - 23H04
      - 7H04
  - - - 23H04
      - 7H04
  - - - 23H04
      - 7H04
  - - - 23H04
      - 7H04
  - - - 23H04
      - 7H04
subscribed_power: 9 kVA
unit_of_measurement: kWh
```

**Comment by vingerha** [comment]
@flouck ... si tu commence d'ajouter que les données sont erronnées p.r. d'Enedis (enedis est la source) il faut commencer là bas. La carte ne peut plus faire que montrer les données fourni
De ton example, je ne voix pas facilement ce que tu voix comme erreurs et je ne vais pas tester le tout comme tu comprends...stp les marqués

**Comment by flouck** [comment]
En fait, il me semble que le problème vient du calcul des pourcentages.
![image](https://user-images.githubusercontent.com/60158607/227323873-7080ea46-916a-4f55-bb5b-99813cd6c55b.png)
"évolution par rapport à semaine" =  ( "semaine courante" - "semaine A-1" ) / "semaine A-1" *100
Donc dans ce cas, ça vaut 9,58%, pas 95%
Pareil pour les autres :
![image](https://user-images.githubusercontent.com/60158607/227325294-05de75d2-5419-4bce-bd99-9908f30e53a8.png)
30,7% et pas -71%

Et pour le % HP, je pense qu'on peut dire :
%HP = (HP) / (HC+HP) *100
Dans ce cas : %HP = 60,4%

**Comment by vingerha** [comment]
Donc, je ne voix pas la deuxième. Hier = 9.61, Hier-1 n'est pas 7.35, tu l'a caché derriere le box mais selon les prix, Mar est PLUS chère que Mer.

Pour la première, encore: ajout ta carte ET les détails du sensor de ce même (!) moment. Ajouter des nouveaux chiffres et cartes qui ne sont pas alignés  n'aide pas du tout avec l'analyse

**Comment by flouck** [comment]
Hello @vingerha, non,, les -1 sont par rapport au même jour/semaine l'année dernière. Par exemple ça compare le 22 mars 2023 avec le 22 mars 2022 il me semble.

**Comment by flouck** [comment]
En fait, c'est pas une question de carte Lovelace car je retrouve les mêmes données dans les attributes.

**Comment by flouck** [comment]
1ère question : 
Sur %HP, es-tu d'accord avec la formule : %HP = (HP) / (HC+HP) *100

2ème question : 
Il faut savoir les % d'évolution s'ils comparent par rapport à la dernière période (la semaine dernière vis-à-vis de cette semaine par exemple) ou par rapport à la même période de l'an passée (par exemple le 22 mars 2023 par rapport au 22 mars 2022). Quand je regarde ce que saniho a écrit sur sa carte quand tu passes ta souris sur chaque case, on voit Semaine A-1 donc je pense que c'est par rapport à la même période de l'an passée.

3ème question :
Toutes ces comparaisons se font bien sur les consommations en kWh et non pas sur les coûts en € ?

Merci :D

**Comment by vingerha** [comment]
Hmm... je pense que je me suis tronpé avec (pauvre) excuses: je ne jamais utilise ces %. et les déscription m'ont mis sur la  mauvais direction car les deux premières ont 2022 dedans .... 
Basé sur les chiffres chez mois, tous les conso de l'année préc. sont plus haut, donc j'attends que les % dans la carte sont soit tout PLUS (résultat positive) soit tout MOINS (consommation moins)
@m4dm4rtig4n est-ce que tu peux confirmer que les calculs ont besoins d'attention?

**Comment by vingerha** [comment]
La carte à eu une maj...stp revoir car les infos n'était pas bon. Les chiffres pour semaine et hier étaient pas pour A-1.
Maintenant les pourcentages et leur données sont aligné (pour moi). version de la carte: 1.4.1

**Comment by m4dm4rtig4n** [comment]
On est bon du coup now ?

**Comment by vingerha** [comment]
J'ai rru les calculs et tout me semsble bon sauf pour HP/HC....car je n'ais pas des données (en BASE) je ne peut pas facilement le tester.

**Comment by m4dm4rtig4n** [comment]
Pour le HC/HP pas besoin de données den BASE dans tt le cas, le calcul est un ratio de valeur en HP & HC en base directement.
D'ailleurs, je pense revoir le système de tag HC/HP car en fin de compte c'est merdique de le stocker directement avec la valeur en BASE et m'oblige à clean le cache lors du changement d'horaire...
