### ISSUE TITLE
[BUG] - Commencer de 'rien', fixé en 14-beta1 mais de retour dans 14-beta3

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata#309]
Reproduction: demarer docker 8.14-beta3 sans cache.db dans data, après les 10s...termine
Faire la même avec 8.14-beta1 continue avec la  recup des données

**Comment by vingerha** [comment]
existe encore

**Comment by vingerha** [comment]
en plus, si on fait l'installation de base avec 08.14-beta1, le bdd est crée avec tous les données
Une maj vers 08.16 après supprime le usage point, je ne sais pas pourquoi

**Comment by m4dm4rtig4n** [comment]
A voir avec la 0.9.0 tt à était rework :)

**Comment by vingerha** [comment]
OK, j'attend et vais vérifier...

**Comment by m4dm4rtig4n** [comment]
Arrivée de la 0.9.0 qui devrait fix le soucis d'ici quelques minutes.

**Comment by vingerha** [comment]
Ça marche... est-ce que tu pourrait écrire un tout petit peu autour la solution (ou le bug)

**Comment by m4dm4rtig4n** [comment]
Je l'ai fix il y a un petit moment, et entre 2 j'ai migrer sur le framework fastapi qui intégre nativement un system de "cronjob" et ca à grandement simplifier le fonctionnement du job.
https://github.com/MyElectricalData/myelectricaldata/blob/4b4c9c401ba869f9462d59f2d4ab7bd991f8045f/app/main.py#L97
