### ISSUE TITLE
Souci nom de domaine myelectra

### ISSUE THREAD

**Issue by Sonic62** [MyElectricalData/myelectricaldata#310]
Hello

le nom de domaine presente un souci ...
Impossible de se rendre sur https://myelectricaldata.fr/

![med](https://user-images.githubusercontent.com/103725660/223580994-77a2cd05-1b6b-469c-889f-965f6a767973.png)
![med1](https://user-images.githubusercontent.com/103725660/223581008-e3fcb834-429d-4921-a6d8-4b8e4e2acbe0.png)

**Comment by flouck** [comment]
Same here
![image](https://user-images.githubusercontent.com/60158607/227320594-1c893b11-36da-4a3f-9f28-d0f2f6dba3d0.png)

**Comment by m4dm4rtig4n** [comment]
Vous avez encore des soucis ou pas ?

**Comment by flouck** [comment]
Oui 
![image](https://user-images.githubusercontent.com/60158607/232247278-1039dbdf-5cbf-4caa-b546-5e9b219de5f5.png)

**Comment by m4dm4rtig4n** [comment]
J'ai fait une demande de "unblackist" auprès d'Avast.

**Comment by m4dm4rtig4n** [comment]
Avast vient de me repondre et ils viennent de retirer le site de leur blacklist.
Ce sera en ligne avec la prochaine MAJ.
