### ISSUE TITLE
[BUG] - Impossible d'accéder à l'interface web du docker

### ISSUE THREAD

**Issue by Veher-el** [MyElectricalData/myelectricaldata#311]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Impossible d'accéder à l'interface du conteneur myelectricaldata sur un port 6000
Les données remontent bien dans influxDB et homeasssistant (entité electricaldata bien reconnue)

**Configuration**
config du docker
`version: "3.9"
services:
  myelectricaldata:
    #container_name: myelectricaldata
    image: m4dm4rtig4n/myelectricaldata:latest-dev 
    restart: unless-stopped
    volumes:
      - "/volume1/docker/myelectricaldata/data:/data"
    environment:
      TZ: Europe/Paris
    ports:
      - 6000:5000
`

**Type d'installation**
Myelectrical data est installé en docker sur mon synology.
Le homeassistant en HassIO via une VM sur le synology.

Or le port 5000 est déjà pris par le Syno, c'est pourquoi j'ai fait la config docker-compose sur le port 5000.
Mais impossible d'accéder à l'interface myelectrical data http://192.168.0.22:6000/ (alors que mes autres dockers sont bien accessibles)

**Version : 8.14.beta3**

Merci pour votre retour

**Comment by vingerha** [comment]
Même comprtement sur mon NUC, La suite marche bien pour les recup, site pas joignable sur 6000 (et non, j'ai pas d'autre processus et oui, j'ai ouvert mon firewall)
```
docker run --name=myelectricaldata_dev -it --restart=unless-stopped -v /home/arjan/docker/myelectricaldata_dev/app:/app -p 6000:5000 -e TZ="Europe/Paris" m4dm4rtig4n/myelectricaldata:0.8.12-beta1
