### ISSUE TITLE
[FEATURES] - ajouter la couleur des jours dans influxdb

### ISSUE THREAD

**Issue by dudu7731** [MyElectricalData/myelectricaldata#314]
Bonjour,

(je remet ce point ici pour un meilleur suivi dans Github)

Serait-il possible d'ajouter les tarifs et couleur jours tempo dans l'export influxdb ?

aujourd'hui je le fait par une autre intégration et un jointure mais le résultat donne un gruyère au niveau couleur de jours (avec 2 intégrations différentes) donc mes données grafana ne sont pas complètes.
![image](https://user-images.githubusercontent.com/117290248/228147026-fcde140f-3402-427a-95cc-ba7bf4808930.png)
![image](https://user-images.githubusercontent.com/117290248/228147105-7f3622fc-204e-4ef1-b57b-51c979eb5cd4.png)

Mes données seraient plus fiables je pense avec un source unique car le recorder de home assistant l'historise pas bien cette info

Merci par avance

**Comment by m4dm4rtig4n** [comment]
Ca arrive avec la 0.9.0 (et sera dispo à partir de la 0.9.0-beta6).
