### ISSUE TITLE
[BUG] - infos daily dans table "consumption" de InfluxDB

### ISSUE THREAD

**Issue by HermesHonshappo** [MyElectricalData/myelectricaldata#364]
**Description du bug**
Hello

Suite à l'update à la 0.8.15 (j'était en 0.8.13 jusqu'à hier), j'ai remarqué que des données détaillées terminent dans la table "consumption"
Je m'en suis aperçu car mes consos mensuelles sont doublées pour la période depuis Février. Ce qui correspond aux périodes 
consumption_max_date et consumption_detail_max_date que j'ai dans ma conf.

On voit là que la conso Avril est de 1,89MWh (infos tirées de InfluxDB dans grafana)
<img width="335" alt="Screenshot 2023-04-20 at 18 37 20" src="https://user-images.githubusercontent.com/97752752/233431655-32679a96-0175-4ae5-9b00-8f2a50ada841.png">

Alors que la carte Saniho montre bien la moitié pour Avril:
<img width="480" alt="Screenshot 2023-04-20 at 18 38 43" src="https://user-images.githubusercontent.com/97752752/233431894-882ac221-8705-4522-a0c6-f4ad62d57e08.png">

J'ai pris quelques screenshots sur Janvier, Février et sur les données d'hier dans Influx. On voit bien la différence.

Entre le 5 et le 6 Janvier, dans la table consumption, mesures en Wh. On a bien une seule mesure, la journalière.
<img width="1396" alt="Screenshot 2023-04-20 at 17 59 13" src="https://user-images.githubusercontent.com/97752752/233432201-760f1607-8158-49aa-beea-71f5aeabc516.png">

Entre le 5 et le 6 Février, cette fois. Toujours dans la table consumption, mesures en Wh. On a plein de mesures, notamment celles en HC et HP et apparemment des mesures horaires.
<img width="1403" alt="Screenshot 2023-04-20 at 18 00 57" src="https://user-images.githubusercontent.com/97752752/233432547-5fd74188-7b71-45ec-b502-afb93147fdd3.png">

Pour la date d'hier. j'ai réussi à afficher les deux types de données, là aussi on voit de l'info horaire en plus de l'info journalière
<img width="1395" alt="Screenshot 2023-04-20 at 18 22 33" src="https://user-images.githubusercontent.com/97752752/233432746-a680d94b-23af-4b26-a03d-4722b2ca72a7.png">

Le souci est apparu hier ou ce matin. Je m'en suis rendu compte en faisant des tests sur mon dashboard grafana ce matin, pour d'autres raisons. ma conso annuelle au m2 etait ce matin 149KMh/m2, alors qu'hier elle était encore à 121KWh/m2

Les seuls changements depuis hier sont:

- le passage en 0.8.15
- le changement de conf pour passer en mode "batch". J'étais encore en mode synchrone, donc l'envoi à Influx prenait des plombes. En passant en mode batching, l'export à InfluxDB va beaucoup plus vite. Peut être la racine du mal?

<details>
<summary>Configuration (config.yaml)</summary>

```
##########
# GLOBAL #
##########
cycle: 14400
debug: true
wipe_cache: false
wipe_influxdb: false
####################
## Home assistant ##
####################
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
####################
##      MQTT      ##
####################
mqtt:
  enable: true
  client_id: enedis_gateway
  hostname: 192.168.13.10
  password: 'XXXX'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'mqtt-hass'
###############
## Influx DB ##
###############
influxdb:
  enable: true
  hostname: 192.168.13.4
  port: 8086
  org: '1d7b8a9cbb3bb068'
  token: 'XXXX=='
  bucket: 'myelectricaldata'
#  asynchronous: 'false'
  method: batching
########################
## MY ELECTRICAL DATA ##
########################
myelectricaldata:
  "MonPDL":
    enable: 'true'
    token: 'XXXXX'
    name: "Maison Magagnosc"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1958'
    consumption_price_hc: '0.1535'
    consumption_price_hp: '0.2117'
    consumption_max_date: "2023-02-01"
    consumption_detail_max_date: "2023-02-01"
    offpeak_hours_0: 1H56-6H56;13H56-16H56 # LUNDI
    offpeak_hours_1: 1H56-6H56;13H56-16H56 # MARDI
    offpeak_hours_2: 1H56-6H56;13H56-16H56 # MERCREDI
    offpeak_hours_3: 1H56-6H56;13H56-16H56 # JEUDI
    offpeak_hours_4: 1H56-6H56;13H56-16H56 # VENDREDI
    offpeak_hours_5: 1H56-6H56;13H56-16H56 # SAMEDI
    offpeak_hours_6: 1H56-6H56;13H56-16H56 # DIMANCHE
#    offpeak_hours: 1H56-6H56;13H56-16H56 # DAILY
#    activation_date_detail: "2021-06-05"
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
#    production_price: '0.0'
#    production_max_date: "2021-06-01"
#    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'true'
    refresh_contract: 'true'
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO, via l'add-on d'Alexbelgium

**Version : 0.8.15**

**Comment by m4dm4rtig4n** [comment]
Hello,

Oui c'est un bug, le soucis à était fix dans la 0.8.16.

Pour un bien il faudrait clean les data de la table consomption avec le mesure_type HC & HP.

**Comment by HermesHonshappo** [comment]
OK je demande à Alexbelgium de publier la 0.8.16, et je tenterai le fix ensuite.
Je vous tiens au jus

**Comment by HermesHonshappo** [comment]
Mise à jour faite sur la 0.8.16 depuis hier matin.

J'ai fait la purge de influx. Pour ceux qui auraient à faire la même chose, la syntaxe, c'est (dans un bash sur la machine ou le docker de influx)
```
influx delete --bucket myelectricaldata --start '2023-01-01T00:00:00Z' --stop $(date +"%Y-%m-%dT%H:%M:%SZ") --org-id 'YOUR_ORG_ID' --predicate '_measurement="consumption" and measure_type="HC"' --token 'YOUR_TOKEN'

influx delete --bucket myelectricaldata --start '2023-01-01T00:00:00Z' --stop $(date +"%Y-%m-%dT%H:%M:%SZ") --org-id 'YOUR_ORG_ID' --predicate '_measurement="consumption" and measure_type="HP"' --token 'YOUR_TOKEN'
```
La start date sera peut être à ajuster si le problème a pourri la base Influx un peu plus loin dans le passé
