### ISSUE TITLE
[BUG] - ERROR : time data '24:00' does not match format '%H:%M'

### ISSUE THREAD

**Issue by Sonic62** [MyElectricalData/myelectricaldata#367]
Hello

apres divers test en version statble et Dev 2 erreurs se produisent

Avec la version Stable 
![Capture d’écran 2023-04-24 193129](https://user-images.githubusercontent.com/103725660/234073019-4561ae44-42df-4878-a1c8-e94557bcc6d2.png)

Avec la version DEV celle-ci
![Capture d’écran 2023-04-24 190753](https://user-images.githubusercontent.com/103725660/234073131-c3f27048-d5b2-4e5f-a491-b5ef36a9f2ab.png)

**Comment by m4dm4rtig4n** [comment]
Pas de fichier de config je clos.
