### ISSUE TITLE
[BUG] - plus de maj de données

### ISSUE THREAD

**Issue by dudu7731** [MyElectricalData/myelectricaldata#371]
**Description du bug**
Obligé de virer le cache pour avoir les derniers jours dans les données
- une relance du container ne règle pas le problème

![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/ce5bb31d-1aed-4484-95ef-91f4b6dac5a3)
![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/7c0730a8-9932-48fa-8ea3-9a24ef02c911)

<details>
<summary>Configuration (config.yaml)</summary>
cycle: 14400
debug: false
wipe_influxdb: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: MyElectricalData
  enable: true
  hostname: XXXXX
  method: asynchronous
  org: production
  port: 8086
  token: XXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: XXXXX
  password: XXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: admin
myelectricaldata:
  'XXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.2062'
    consumption_price_hc: '0.114'
    consumption_price_hp: '0.1508'
    enable: 'true'
    name: Home Enedis
    offpeak_hours_0: 22h00-06h00
    offpeak_hours_1: 22h00-06h00
    offpeak_hours_2: 22h00-06h00
    offpeak_hours_3: 22h00-06h00
    offpeak_hours_4: 22h00-06h00
    offpeak_hours_5: 22h00-06h00
    offpeak_hours_6: 22h00-06h00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: XXX
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 0.8.16**

**Comment by dudu7731** [comment]
juste pour information, mon environnement de test sous docker n'a pas ce bug

**Comment by m4dm4rtig4n** [comment]
@dudu7731 les données ne sont pas dans l'interface web, mais tu peut me confirmer qu'elle sont bien présente dans HA ou l'influxdb ?

**Comment by dudu7731** [comment]
voila les screen : 
![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/3dab647d-7125-4c72-90fa-4c4f2fec2f0c)
![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/c7c30dc5-c6b3-46d7-bb38-596c245cfe04)
![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/c1e3b70e-90e8-45f7-954a-c02b5b058b23)

**Comment by pbranly** [comment]
De mon côté les données n’évoluent plus jamais à partir du reboot du container

**Comment by m4dm4rtig4n** [comment]
Je pense que le soucis provient du fait que c'est un process externe qui vient faire l'import des données tt les x minutes.
Comme le process est sur un autre thread, l'object qui contient les données afficher dans l'interface n'est pas à jours...

Je viens d'ajouter un `session.expire_all()` sur tt les objects a chaque appel de la page des points de livraison qui devrait forcer un refresh des data.
Je vais sortir le fix dans la 0.9.0-beta2, à tester :)

**Comment by m4dm4rtig4n** [comment]
La 0.9.0-beta2 est disponible.

**Comment by m4dm4rtig4n** [comment]
Bon je croise le doigt, mais sur la beta5 je pense que je suis bon ! :D

**Comment by m4dm4rtig4n** [comment]
#302
