### ISSUE TITLE
[BUG] - Lien sur le consentement enedis

### ISSUE THREAD

**Issue by Veher-el** [MyElectricalData/myelectricaldata#372]
**Description du bug**
Bonjour
Je suis arrivé à expiration de mon consentement : les logs montrent que le PDL et le token ne sont pas alignés et qu'un renouvellement de consentement est demandé.
or le lien pour faire le consentement d'enedis affiche 500 internal error.

Je sais que cela ne vient mais de myelectricaldata en tant que tel mais peut être ont ils changé la méthode.
En tout cas, je ne peux plus faire le renouvellement pour obtenir le token.
J'ai tenté de les joindre par tchat mais aucune vraie réponse à cette heure

Une idée pour obtenir le renouvellement du consentement ou token ?
Merci
<details>
<summary>Configuration (config.yaml)</summary>

```yaml
pas de changement sur mon yaml
```
</details>

**Type d'installation**
- [x] Docker

**Version : 8.16**

**Comment by m4dm4rtig4n** [comment]
Le soucis est chez Enedis depuis quelques jours (semaine maintenant).

![image](https://github.com/MyElectricalData/myelectricaldata/assets/7872518/e80efbb1-0edd-4655-b468-10de34931d39)

Le fix n'est pas dans leurs sprint depuis 1 mois quasiment...

**Comment by macfly92** [comment]
Il y a du progrès !
On est passé de l'erreur 500 à une erreur 404 😒
![image](https://github.com/MyElectricalData/myelectricaldata/assets/24654951/54855a88-894c-43ad-942c-a5e1f1733103)

**Comment by T0FFF** [comment]
Bonjour, un grand merci pour ce dev bien pratique :)
Du coté d'Enedis, ça semble avancer un peu après 2 semaines avec des erreurs 500 puis 404... là, j'ai la page qui s'affiche avec mon point de livraison et la case à cocher pour valider le consentement mais je ne peux pas valider (j'ai essayé avec 2 navigateurs différents) :(

**Comment by Veher-el** [comment]
J'ai fait exactement la même aujourd'hui 😁.
J'ai appelé le support client, ils reconnaissent le bug et travaillent
dessus... Encore un peu de patience

Le ven. 16 juin 2023, 16:42, Christophe LE COZ ***@***.***> a
écrit :

**Comment by Veher-el** [comment]
C est bon, le bug a été corrigé côté enedis.
Myelectrical est bien réalimenté avec le consentement et la génération du nouveau token

**Comment by Veher-el** [comment]
Consentement corrigé par enedis

**Comment by Jielde** [comment]
Bug de nouveau...
![image](https://github.com/MyElectricalData/myelectricaldata/assets/11017153/2412e469-9d31-4d6b-8419-18ee410c4374)
