### ISSUE TITLE
[FEATURES] - Compte ENEDIS professionnel

### ISSUE THREAD

**Issue by myfp31** [MyElectricalData/myelectricaldata#378]
Bonjour,

D'abord un grand merci, je vais surement l'utiliser à titre personnel.
Je me permets de rebondir sur ce [ticket](https://github.com/MyElectricalData/myelectricaldata/issues/235). 
Je cherche en priorité pour une TPE, à suivre la consommation électrique et à optimiser le fonctionnement de la pompe à chaleur.
Si j'ai bien lu sur la page https://myelectricaldata.fr/ en tant que professionnel, il est possible de passer un contrat et de respecter leur cahier des charges pour interroger leur API.
Aussi sera t'il possible de partager le code qui va interroger leur API pour https://myelectricaldata.fr/ ?
Est-ce que cela me permettra de récupérer les données de la société ou uniquement de clients particuliers?
J'ai un doute en tentant de faire les premières étapes sur le datahub d'Enedis.

Merci,

**Comment by m4dm4rtig4n** [comment]
Merde j'était sur d'avoir répondu à ton issue mais non en fait...

J'ai échanger avec Enedis à ce sujetn, et le soucis est que les l'API Datahub n'est pas connecter au compte professionnel.
Il n'est malheuresment donc pas possible de récupérer les informations de compteur pro via le datahub :/

Après il y a d'autre API chez Enedis faudrait eplucher leurs différentes offres.

Pour le code de la passerelle, pk pas faudrait juste que je prennent le temps de faire une passe sur le code pour le clean.

**Comment by myfp31** [comment]
Bonjour,

OK donc, il va falloir que je suive tout le process décrit dans les docs en vas de page : https://www.enedis.fr/professionnels-et-entreprises-jaccede-mes-donnees-de-consommation-et-de-production-delectricite
Je vais voir quand je trouve le temps de le faire.... Je te recontacterai si je vois que le code pourrait être proche.

Merci beaucoup.
