### ISSUE TITLE
[HELP] - Comment migrer de myEnedis à MyElectricalData ?

### ISSUE THREAD

**Issue by cosygarcia** [MyElectricalData/myelectricaldata#379]
J'utilisais jusqu'à présent myEnedis mais depuis quelques temps il n'y a pas plus de données. Comment migrer sous MyElectricalData ?

Mon installation :
Home Assistant 2023.6.2
Supervisor 2023.07.1
Interface utilisateur : 20230608.0 - latest
OS : Debian 11 bullseye

**Comment by m4dm4rtig4n** [comment]
Tu peut utiliser l'addon dispo sur le repo d'@alexbelgium si tu veut :)
https://github.com/alexbelgium

**Comment by m4dm4rtig4n** [comment]
Nop les données ne seront pas migrer.
L'addon MyEnedis utilise le cache de Home Assistant que MyElectricalData son propore cache.
