### ISSUE TITLE
[BUG] - préciser l'encodage UTF-8 dans les sources HTML

### ISSUE THREAD

**Issue by grrosminet** [MyElectricalData/myelectricaldata#382]
**Description du bug**
Les accents ressortent mal dans Firefox : "_Afin d'utiliser MyElectricalData, il est nÃ©cessaire de rÃ©aliser vos consentements sur la passerelle dÃ©diÃ©e._"
Note : le problème n'est pas présent dans chrome

<details>
<summary>Configuration (config.yaml)</summary>
cycle: 14400
debug: false
home_assistant:
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: mqtt.maison.lan
  password: 'null'
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: 'null'
myelectricaldata:
  097**************8:
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2062'
    consumption_price_hc: '0.1615'
    consumption_price_hp: '0.2228'
    enable: 'true'
    name: maison
    offpeak_hours_0: 2h04-7h04;14h04-17h04
    offpeak_hours_1: 2h04-7h04;14h04-17h04
    offpeak_hours_2: 2h04-7h04;14h04-17h04
    offpeak_hours_3: 2h04-7h04;14h04-17h04
    offpeak_hours_4: 2h04-7h04;14h04-17h04
    offpeak_hours_5: 2h04-7h04;14h04-17h04
    offpeak_hours_6: 2h04-7h04;14h04-17h04
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: **********************
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508

```yaml

```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 0.9.0**
![Screenshot_20230727_100213](https://github.com/MyElectricalData/myelectricaldata/assets/3082795/ae085f89-b638-46c0-9c62-f819fca60e89)

**Comment by m4dm4rtig4n** [comment]
Hello, il y a un ticket en cours sur l'addon directement chez @alexbelgium :
https://github.com/alexbelgium/hassio-addons/issues/914
