### ISSUE TITLE
[FEATURES] - Ajout des sensors HA EcoWatt J+1 et J+2

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata#386]
Basé sur _ecowatt:
- même données 
- mais pas des maj des heures dans la journée, donc begin/end 7 - 21
- nom peu importante, je propose _ecowatt_j1 et _ecowatt_j2

Dans la carte Linky, ça ce voit comme ça (ouvert à discussion)

![image](https://github.com/MyElectricalData/myelectricaldata/assets/44190435/79a1af89-db1b-403c-a9be-e28095d7d243)

**Comment by vingerha** [comment]
J'ajoute que dans MQTT J2 n'est pas J+2
J0: aujourd'hui
J1: demain
J2: hier

**Comment by vingerha** [comment]
PR fournis...j'attend ton retour ou merge :)

**Comment by m4dm4rtig4n** [comment]
On afficherais pas plutot directement 24h (en j / j+1 / j+2) avec uniquement les créneaux en tenssion du style :
![image](https://github.com/MyElectricalData/myelectricaldata/assets/7872518/f3379973-d629-49d1-9b71-90e752734624)

**Comment by m4dm4rtig4n** [comment]
En ligne avec la 0.9.1
