### ISSUE TITLE
[HELP] - Show ratio year

### ISSUE THREAD

**Issue by slider07210** [MyElectricalData/myelectricaldata#390]
**Description de la fonctionnalité** : 
Problème avec le Show ratio year avec la content-card-linky

**Type d'installation :**
HassIO sur une machine virtuel 
MyElectricalData dev 0.9.1b11

Bonjour,
Je me permets de vous contacter pour vous partager mon problème de remontée d'information concernant le Show ratio year avec la content-card-linky Nan% par rapport à 2022 s'affiche alors que le ratio mois en cours et mois précédent fonctionne bien.

Les attributs Current year et Current year last year sont pourtant présents dans l'entité.

Merci pour aide.

![Capture d’écran 2023-08-12 094255](https://github.com/MyElectricalData/myelectricaldata/assets/60269193/48a851c7-ef8b-4424-84b8-02b7e04073fe)

**Comment by vingerha** [comment]
Pourquoi t'ouvres des tickets dans plusieurs endroit? Ça n'aide pas trops.
@m4dm4rtig4n tu peux le fermer car solution via la carte

**Comment by slider07210** [comment]
Désolé je ne savais pas si le problème provenait de la card ou de l'intégration.
En tout cas merci beaucoup pour la résolution.
Bonne journée
