### ISSUE TITLE
[HELP] - Problème Python docker home assistant 

### ISSUE THREAD

**Issue by Arthurochrome** [MyElectricalData/myelectricaldata#393]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**
Bonjour,
Quand je lance le docker. J'ai des erreurs python. 
J'ai pourtant bien adapté le config.yaml..
Voici des captures d'écran d'erreur et du config.yaml.
Merci d'avance. 
**Type d'installation**
Docker, HassIO ?
Docker

**Version : X.X.X**
Dernière version

**Comment by Arthurochrome** [comment]
![Uploading Screenshot_20230813-164709.png…]()

**Comment by Arthurochrome** [comment]
![Screenshot_20230813-164416](https://github.com/MyElectricalData/myelectricaldata/assets/142165944/2739f259-22c5-4415-8e9a-de6820250908)

**Comment by Arthurochrome** [comment]
![Uploading Screenshot_20230813-164709.png…]()

**Comment by pbranly** [comment]
Bonjour
Tu as une bonne partie de la raison dans ton log. Tu n’arrives pas à te connecter sur influx . Quelle config as tu ? Influx 1.8 ou 2.x ?

**Comment by Arthurochrome** [comment]
Bonjour,
Merci pour ta réponse rapide.
Je suis en 2.x. 
J'ai repris la configuration du yaml en exemple.
Voici une capture d'écran de mon config.yaml
![Screenshot_20230813-164709](https://github.com/MyElectricalData/myelectricaldata/assets/142165944/3baff12c-cd21-4f1e-8d61-3229661d7625)

**Comment by Arthurochrome** [comment]
Au niveau du tocken de influx, il faut mettre la clef d'acces comme dans la conf du pdl?

**Comment by pbranly** [comment]
Ne mets pas ton numéro de pdl en clair dans tes messages 
Sinon suis la doc pour influx 
https://github.com/MyElectricalData/myelectricaldata/wiki/03.-Configuration

**Comment by Arthurochrome** [comment]
J'essaye de suivre la doc. J'ai mis mon ip au niveau de l'hostname. Mais j'ai toujours une connexion refusé.

"2023-08-13 18:33:47.343 -     INFO : Connect to InfluxDB 192.168.1.192:8086
2023-08-13 18:33:47.352 - CRITICAL : ['Impossible de se connecter à la base influxdb.', '', 'Vous pouvez récupérer un exemple ici :', 'https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file']
2023-08-13 18:33:47.352 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-13 18:33:47.352 -     INFO :   MÉTHODE D'IMPORTATION : SYNCHRONOUS
2023-08-13 18:33:47.353 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection("

**Comment by Arthurochrome** [comment]
Tout est sur le même serveur. Je ne pense pas que ça soit un problème pare-feu. Une idée ?

**Comment by pbranly** [comment]
Non ta config influx ne soit pas être bonne .
As tu créé ta base ? Ton token influx est il bon ?
Etc …

**Comment by Arthurochrome** [comment]
Bonjour @pbranly Je n'avais pas vu qu'il fallait installer aussi influx. Je pensais que tout était packagé dans le conteneur myelectridata.
Je veux juste faire remonter mes infos enedis dans Home assistant. Pourquoi on utilise pas la base de données home assistant ?
Désolé pour mes questions. Je suis novice ds ce domaine, sujet très intéressant 👍

**Comment by pbranly** [comment]
Tu n’as effectivement pas besoin de influx
Dans ce cas, mets le en false dans la config

**Comment by Arthurochrome** [comment]
Super merci, ça fonctionne. Il faut pas contre que je trouve le bon affichage pour mon dashboard.
