### ISSUE TITLE
[HELP] - import dans influxdb

### ISSUE THREAD

**Issue by Arthurochrome** [MyElectricalData/myelectricaldata#394]
Bonjour,
J'ai créé une base influxdb et mes identifiants dans le fichier de config mais il ne trouve pas la base. Une idée du problème ?
Merci d'avance.
![Screenshot_20230819-185826](https://github.com/MyElectricalData/myelectricaldata/assets/142165944/611ad1f3-59b2-4122-925e-9ef08e98a105)

**Type d'installation**
Docker

**Version : X.X.X**
Version 1.8 influxdb

**Comment by m4dm4rtig4n** [comment]
Hello,

Sans fichier de configuration ne je peut t'aider.

**Comment by Arthurochrome** [comment]
Hello, j'avais mal renseigné le fichier. Merci
