### ISSUE TITLE
[FEATURES] - Fonctionnement avec HASS Core, ? sans docker ou Addons

### ISSUE THREAD

**Issue by karba78** [MyElectricalData/myelectricaldata#404]
Bonjour
Impossible d installer sur HACS comme vous l indiquez
seulement sur les versions d HA avec Addons ou bien docker.
avez vous l intention de fournir une version qui s installe sur les HASS Core avec HACS ?
Merci

**Comment by pbranly** [comment]
Il n'est défini nulle part que myelectricaldata est installable avec HACS 
seulement en add on sur une installation supervised ou en docker

**Comment by m4dm4rtig4n** [comment]
Hello @karba78 ,

MED (MyElectricalData) est prévu pour fonctionner uniquement en mode Docker (et donc compatible avec les addon HA).
Et je n'ai pas prévu de faire fonctionner MED autrement qu'en docker.

Après je pense qu'il est possible de démarrer le service sans docker avec quelques petites bidouilles.
