### ISSUE TITLE
[HELP] -  

### ISSUE THREAD

**Issue by Tays005** [MyElectricalData/myelectricaldata#405]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**
**Type d'installation HassIO 

**Version : 0.9.1*

Bonjour, je viens d'installer MyElectricalData je peux que tout est nickel à ce niveau là. Par contre je crois que j'ai plus un soucis un niveau du consentement, que je fais un test  via la ligne de commande ( https://www.myelectricaldata.fr/valid_access/******** ) je reçois : {"detail":"Not authenticated"} 

et sur le module il ne voit pas ma ligne.
![image](https://github.com/MyElectricalData/myelectricaldata/assets/96090543/467009c9-63e9-4dd5-9d84-00456eb94a4a)

par contre dans les logs

connection serveur MQTT ok
connection serveur Influx ok
pdl OK

Cordialement.

**Comment by m4dm4rtig4n** [comment]
Partage ton fichier de conf anonymisé stp :)

**Comment by Tays005** [comment]
Voici ma config 👍 

cycle: 14400
debug: false
home_assistant:
  card_myenedis: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: "myelectricaldata/autogen"
  enable: true
  hostname: a0d7b954-influxdb
  method: synchronous
  org: "-"
  port: 8086
  token: myelectricaldata:*******
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: "************"
  password: "************"
  prefix: myelectricaldata
  retain: true
  qos: 0

myelectricaldata:
  1*************4:
    activation_date_daily: ""
    activation_date_detail: ""
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: "2021-01-01"
    consumption_max_date: "2021-01-01"
    consumption_price_base: "0.1415"
    consumption_price_hc: "0.0984"
    consumption_price_hp: "0.1315"
    enable: true
    name: "Maison"
    offpeak_hours_0: "22H24-06H24"
    offpeak_hours_1: "22H24-06H24"
    offpeak_hours_2: "22H24-06H24"
    offpeak_hours_3: "22H24-06H24"
    offpeak_hours_4: "22H24-06H24"
    offpeak_hours_5: "22H24-06H24"
    offpeak_hours_6: "22H24-06H24"
    plan: HC/HP
    production: false
    production_detail: false
    production_detail_max_date: ""
    production_max_date: ""
    production_price: 0
    refresh_addresse: true
    refresh_contract: true
    token: *************************************

**Comment by m4dm4rtig4n** [comment]
Entre triple quote stp sinon le format est perdu.
```
exemple
```

**Comment by Tays005** [comment]
Je viens de le voir :)

**Comment by Tays005** [comment]
ok je test ça merci

**Comment by Tays005** [comment]
ALors il y a du mieux, il voit PDL quand je lance Myelectricaldata mais : 
![image](https://github.com/MyElectricalData/myelectricaldata/assets/96090543/efac4106-4be6-4b35-b5b3-c91414cb3152)

**Comment by Tays005** [comment]
![image](https://github.com/MyElectricalData/myelectricaldata/assets/96090543/2c512c50-976b-4a6a-b9a4-c7d420ba452f)

Bon j'ai refait la demande de consentement a priori cela doit être bon merci de votre aide je vous confirme ça dans la journée.
