### ISSUE TITLE
[HELP] - mise à jour 0.9.2

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/myelectricaldata#412]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**

**Type d'installation**
HassIO

**Version : X.X.X**

La mise à jour ne se fait pas et n’apparaît nulle part. Faut il la forcer ?

**Comment by m4dm4rtig4n** [comment]
Sur HassIO il faut parfois attendre un peu avant que la maj pop sur les addons.
Le temps que le repo d'Alexbelgium ce resynchrnise.

**Comment by Jeepmg** [comment]
J'attends depuis 9 heures sans succès.

**Comment by m4dm4rtig4n** [comment]
@alexbelgium, j'ai un update de la 0.9.2 de MyElectricalData qui ne remonte pas sur ton dépôt :D 
Tu sais jeter un œil stp ?

Merci d'avance :)

**Comment by alexbelgium** [comment]
Hello, l'update se fait tous les samedis pour mes 81 Add-ons

**Comment by Jeepmg** [comment]
Effectivement, il faut "attendre un peu".

Il n'y a pas un plan B ? 

Merci pour tout.

**Comment by m4dm4rtig4n** [comment]
> Effectivement, il faut "attendre un peu".
> 
> Il n'y a pas un plan B ?
> 
> Merci pour tout.

A part l'installer sans passer par HassIO en mode docker classique non.
