### ISSUE TITLE
[Help] - Récupéré sensors pour carte perso , style Apex , graphe etc...

### ISSUE THREAD

**Issue by c7274864** [MyElectricalData/myelectricaldata#413]
Bonsoir
Super l'idée de tout remonté la conso dans le lovelace Energie , beau travail et félicitation :-)
Un seul hic , mais tu y es pour rien et le décalé pour récupéré les infos ...

Mais est il possible de récupéré ses infos pour ce faire des cartes avec apex par exemple ?

**Comment by m4dm4rtig4n** [comment]
Hello,

Oui tu trouvera même des exemples dans le post suivant si tu veut :)
https://forum.hacf.fr/t/les-cartes-et-myelectricaldata/19996
