### ISSUE TITLE
[HELP] - 

### ISSUE THREAD

**Issue by olivvv59** [MyElectricalData/myelectricaldata#414]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**

bonjour,

je n'arrive pas à 
récupérer un token sur 
https://mon-compte-particulier.enedis.fr/donnees/

l url a changé? ou faut attendre que enedis remettre la page en service?

je vous remercie pour votre aide 🙂

**Type d'installation**
Docker, HassIO ?

**Version : X.X.X**

**Comment by m4dm4rtig4n** [comment]
Soucis chez Enedis, une migration est en cours chez eux, il faut attendre.

**Comment by olivvv59** [comment]
Merci pour ta réponse rapide 😌

j'ai que ça remarchait aujourd'hui.

j'ai essayé de supprimer sandbox dans l url de redirection mais sans succès.

peut-être, ce n'est pas encore bien rétabli.

Le mer. 20 sept. 2023, 12:52, m4dm4rtig4n ***@***.***> a
écrit :
